# -*- coding: utf-8 -*-
"""PromptLab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i0KywHUFTZZoQsyhvvMh9qzCJLz8HQzg
"""

!pip install transformers torch pandas reportlab

# IMPORTS
from transformers import pipeline, set_seed, GPT2LMHeadModel, GPT2Tokenizer
import torch
import pandas as pd

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors


# SETUP
set_seed(42)

device = 0 if torch.cuda.is_available() else -1
torch_device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

generator = pipeline(
    "text-generation",
    model="gpt2",
    device=device
)

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2").to(torch_device)
tokenizer.pad_token = tokenizer.eos_token


# PROMPTS
prompts = [
    "A robot found a diary that could predict the future,",
    "Humans colonized Mars and discovered a hidden civilization,",
    "An AI started dreaming and created a new universe,",
    "The internet suddenly became alive and started talking to humans,",
    "A spaceship reached a planet where time flows backwards,"
]


# CREATIVITY SCORE
def creativity_score(text):
    words = text.split()
    return len(set(words)) / len(words) if len(words) > 0 else 0


# STORAGE
results_log = []


# MAIN LOOP
for prompt in prompts:

    print("\n" + "="*80)
    print("PROMPT:", prompt)

    # MULTI-SAMPLE GENERATION
    outputs = generator(
        prompt,
        max_new_tokens=60,
        num_return_sequences=3,
        temperature=0.8,
        top_p=0.95,
        do_sample=True,
        pad_token_id=50256
    )

    samples = []
    scores = []

    for i, out in enumerate(outputs):
        text = out["generated_text"]
        score = creativity_score(text)

        samples.append(text)
        scores.append(score)

        print(f"\nSAMPLE {i+1}:\n{text}")
        print("Creativity Score:", round(score, 3))

    avg_score = sum(scores) / len(scores)

    print("\nCREATIVITY AVG:", round(avg_score, 3))


    # PIPELINE OUTPUT
    pipe_out = generator(
        prompt,
        max_new_tokens=60,
        num_return_sequences=1
    )[0]["generated_text"]

    # MANUAL OUTPUT
    manual_inputs = tokenizer(prompt, return_tensors="pt").to(torch_device)

    manual_out = model.generate(
        **manual_inputs,
        max_new_tokens=60,
        temperature=0.7,
        top_p=0.9,
        do_sample=True,
        repetition_penalty=1.2
    )

    manual_text = tokenizer.decode(manual_out[0], skip_special_tokens=True)

    print("\nPIPELINE OUTPUT:\n", pipe_out)
    print("\nMANUAL OUTPUT:\n", manual_text)


    # STORE DATA
    results_log.append({
        "prompt": prompt,
        "sample_1": samples[0],
        "sample_2": samples[1],
        "sample_3": samples[2],
        "avg_creativity": avg_score,
        "pipeline_output": pipe_out,
        "manual_output": manual_text
    })


# CREATE CSV
df = pd.DataFrame(results_log)
df.to_csv("gpt2_clean_experiment.csv", index=False)
print("\nCSV Saved!")


# CREATE PDF
pdf_file = "GPT2_Experiment_Report.pdf"
doc = SimpleDocTemplate(pdf_file)

styles = getSampleStyleSheet()
content = []

content.append(Paragraph("GPT-2 Text Generation Experiment", styles["Title"]))
content.append(Spacer(1, 12))

summary = f"Total Prompts: {len(df)}"
content.append(Paragraph(summary, styles["Normal"]))
content.append(Spacer(1, 12))


table_data = [["Prompt", "Avg Creativity"]]

for _, row in df.iterrows():
    table_data.append([
        row["prompt"][:50] + "...",
        round(row["avg_creativity"], 3)
    ])

table = Table(table_data)

table.setStyle(TableStyle([
    ("BACKGROUND", (0,0), (-1,0), colors.grey),
    ("TEXTCOLOR", (0,0), (-1,0), colors.whitesmoke),
    ("GRID", (0,0), (-1,-1), 0.5, colors.black),
    ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
]))

content.append(table)

doc.build(content)

print("\nPDF Generated Successfully!")